path_to_weights: data/weights
ld_plink_prefix: data/LDREF_b38ids/1000G.EUR
modalities:
- alt_polyA
- alt_TSS
- expression
- isoforms
- splicing
- stability
# traits:
# - UKB_1160_Sleep_duration
# - UKB_1180_Morning_or_evening_person_chronotype
# - UKB_1200_Sleeplessness_or_insomnia
