## Upload to temporary repo location (-s prevents reuploading files if unchanged at destination):
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/check_repo.py /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/covariates Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/file_tree.txt /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/info /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/processed /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/QTLs /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/README.md /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/RNA_phenotypes /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/TWAS_associations /Pantry_data/"
sbatch --wrap="~/tools/Dropbox-Uploader/dropbox_uploader.sh -s upload repo/TWAS_weights /Pantry_data/"
